name: Go Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.x'

    - name: Install dependencies
      run: go mod download

    - name: Run tests with coverage
      run: |
        mkdir -p coverage
        go test -v ./... -coverprofile=coverage/coverage.out

    # Optional Step: Display coverage in the console
    - name: Show coverage
      run: go tool cover -func=coverage/coverage.out


    - name: Upload to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: coverage/coverage.out
        flags: unittests
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }} # required
        verbose: true # optional (default = false)
